### ISSUE TITLE
something to talk

### ISSUE THREAD

**Issue by yuanjinzhong** [jd-opensource/joylive-agent#1]
cool, 今天我们公司分享内部rpc框架无感升级,也是基于java agent 来实现的, 约等于目前提的比较多的概念: proxy less mesh

然后在github上就看到贵司的仓库了,

被回旋镖击中的感觉

**Comment by chenzhiguo** [comment]
如果规则在此方面有共同的目标与兴趣，欢迎共建。

**Comment by yuanjinzhong** [comment]
> 如果贵司在此方面有共同的目标与兴趣，欢迎共建。

好滴，我先理解一下咱们这个仓库所做的事情呢

**Comment by hexiaofeng** [comment]
加个联系方式吧

**Comment by yuanjinzhong** [comment]
> 加个联系方式吧

佬,wx:y592651
Gmail: azhong.gmall@gmail.com
