### ISSUE TITLE
Support the policy subscription function through Nacos configuration

### ISSUE THREAD

**Issue by chenzhiguo** [jd-opensource/joylive-agent#18]
**Is your feature request related to a problem? Please describe.**

Currently, we have implemented several methods to obtain policies through a fixed API. However, these methods are not general enough, and we hope that the policy content can be subscribed to through a configuration center (such as Nacos).

The implementation location is: `joylive-implement/joylive-service`
For reference: `joylive-implement/joylive-service/joylive-service-multilive`

**Comment by hexiaofeng** [comment]
with live policy

**Comment by hexiaofeng** [comment]
There are many config centers, so design a config api，watch config change event.

**Comment by zinu-x** [comment]
1、Design a Config API, watch config change event.
2、The API  supports Nacos.
3、Sync Policy by the API.
