### ISSUE TITLE
关于joylive-agent项目package建议

### ISSUE THREAD

**Issue by mayl666** [jd-opensource/joylive-agent#3]
您好：
了解到目前：
joylive-bootstrap-api实现 joylive-implement
joylive-core-api 实现 joylive-core-framework，joylive-implement
joylive-governance-api 实现 joylive-plugin
希望能够：
core的实现和bootstrap的实现分离，可以api单一实现。基于代码的包层次的分层可以更清晰。
不知道我的建议合理不。

**Comment by hexiaofeng** [comment]
joylive-agent做了类隔离，joylive-bootstrap-api是由应用类加载器加载，里面放了一些字节码增加的一些类，这些类在应用调用的时候需要，同时也是框架需要的。所以有这个依赖关系。joylive-core-api依赖于joylive-bootstrap-api

**Comment by mayl666** [comment]
那是否可以再创建一个bootstrap-impl包实现bootstrap-api。
core-api实现：将joy-implement中部分core-api 实现移动到joylive-core-framework。
bootstrap-api实现：将joy-implement中部分bootstrap-api 实现移动到bootstrap-impl。
core-api依赖bootstrap-api实现放到到joylive-core-framework。

**Comment by mayl666** [comment]
比如：
1、joylive-bootstrap-api中com.jd.live.agent.bootstrap.bytekit移动到core-api
2、joylive-core-api中com.jd.live.agent.core.bootstrap 移动到joylive-bootstrap-api
3、joylive-core-api中com.jd.live.agent.core.plugin 移动到joylive-governance-api
4、joylive-implement中joylive-command、joylive-eventbus、joylive-expression移动到joylive-core-framework下面

**Comment by hexiaofeng** [comment]
com.jd.live.agent.bootstrap.bytekit，这个里面的类应用访问需要，以前我们是放在core-api里面的，发现应用报错，才放到bootstrap-api里面的。

**Comment by hexiaofeng** [comment]
joylive-implement都考虑到后续扩展需要，可以替换掉。原来是期望framework都不包含实现，只有启动主流程的。后来发现扩展，注入这些实现放在implement里面，在启动里面解决不了依赖顺序，才放在了framework里面。

**Comment by hexiaofeng** [comment]
这块后续可以优化

**Comment by mayl666** [comment]
注入、扩展、代理。都可以单独出来核心功能。如果他们有依赖，可以互相引入吧。先这样吧，不issue可以关了

**Comment by hexiaofeng** [comment]
如果有兴趣的话，可以加入到项目中来。

**Comment by mayl666** [comment]
等我先研究明白了再加入吧，希望贵司把ducc开源出来。对ducc情有独钟。

**Comment by hexiaofeng** [comment]
在做2.0的设计，涉及到类加载器，请查阅文档

**Comment by mayl666** [comment]
我看了下2.0的文档，其中core-bootstrap 可以不在core根包下面吗？bootstrap-api在另一个包里
