### ISSUE TITLE
SofaRpc Demo

### ISSUE THREAD

**Issue by chenzhiguo** [jd-opensource/joylive-agent#5]
Is your feature request related to a problem? Please describe.

Currently, our project has some demo examples to verify the functionality of joylive-agent, including frameworks such as Spring Cloud, Dubbo3, and Dubbo2.7. However, there are still some demos that we have adapted but are missing, such as the SofaRpc.

目前我们项目里有一些demo示例用于验证joylive-agent的功能，包括spring cloud，dubbo3， dubbo2.7等框架。但是依然有一些我们做了适配，但是还缺少的demo示例。比如SofaRpc。

Describe the solution you'd like

We hope that volunteers can provide an example project for the joylive-agent project based on the Demo of Dubbo3 or Dubbo2.7 versions, for SofaRpc.

我们希望有志愿者能根据Dubbo3或者Dubbo2.7版本的Demo，为joylive-agent工程提供基于SofaRpc的示例工程。

**Comment by yuanjinzhong** [comment]
如果还没被认领,我试一下 @chenzhiguo

**Comment by hexiaofeng** [comment]
有进展吗？

**Comment by yuanjinzhong** [comment]
> 有进展吗？

@hexiaofeng 峰哥，最近比较忙，我接下来两周看下呢
